# 1. 데이터 불러오기

In [3]:
import pandas as pd

data = pd.read_csv("./hand_data.csv", header=None)
data.head()

,0,1,2,3,4,5,6,7,8,9,...,54,55,56,57,58,59,60,61,62,63
0,0.624676,0.634969,4.125314e-07,0.607056,0.590262,-0.019363,0.617399,0.537908,-0.028162,0.654570,...,0.714701,0.514989,-0.034731,0.702284,0.528157,-0.034967,0.689110,0.540892,-0.032329,Sissors
1,0.645132,0.638345,4.264571e-07,0.630673,0.592792,-0.019441,0.644290,0.541795,-0.028450,0.682910,...,0.736488,0.526884,-0.035484,0.723938,0.540022,-0.034202,0.710659,0.551803,-0.030152,Sissors
2,0.640712,0.644823,4.185136e-07,0.620354,0.601241,-0.016743,0.625203,0.549681,-0.025054,0.659432,...,0.719486,0.513861,-0.035997,0.707416,0.529387,-0.033411,0.695340,0.546181,-0.028114,Sissors
3,0.536404,0.619920,4.116136e-07,0.499182,0.625870,-0.025321,0.465530,0.598687,-0.037203,0.457701,...,0.473386,0.459782,-0.040711,0.481725,0.480981,-0.041110,0.490151,0.503639,-0.036479,Sissors
4,0.497161,0.580219,4.147568e-07,0.460030,0.586002,-0.020350,0.426831,0.560021,-0.028712,0.417785,...,0.437086,0.433737,-0.032320,0.443381,0.453562,-0.034293,0.450911,0.475329,-0.031802,Sissors

In [6]:
# 컬럼 이름 바꾸기 
# 열 개수: 64개 (= 21개 * 3(XYZ) + label)
# columns -> x1 y1 z1 x2 y2 z2 ..... label
columns = []
for i in range(21):
    columns.extend([f"x{i+1}", f"y{i+1}", f"z{i+1}"])
columns.append("label")

print(len(columns))
print(columns)

64
['x1', 'y1', 'z1', 'x2', 'y2', 'z2', 'x3', 'y3', 'z3', 'x4', 'y4', 'z4', 'x5', 'y5', 'z5', 'x6', 'y6', 'z6', 'x7', 'y7', 'z7', 'x8', 'y8', 'z8', 'x9', 'y9', 'z9', 'x10', 'y10', 'z10', 'x11', 'y11', 'z11', 'x12', 'y12', 'z12', 'x13', 'y13', 'z13', 'x14', 'y14', 'z14', 'x15', 'y15', 'z15', 'x16', 'y16', 'z16', 'x17', 'y17', 'z17', 'x18', 'y18', 'z18', 'x19', 'y19', 'z19', 'x20', 'y20', 'z20', 'x21', 'y21', 'z21', 'label']

In [7]:
data.columns = columns

In [8]:
data.head()

,x1,y1,z1,x2,y2,z2,x3,y3,z3,x4,...,x19,y19,z19,x20,y20,z20,x21,y21,z21,label
0,0.624676,0.634969,4.125314e-07,0.607056,0.590262,-0.019363,0.617399,0.537908,-0.028162,0.654570,...,0.714701,0.514989,-0.034731,0.702284,0.528157,-0.034967,0.689110,0.540892,-0.032329,Sissors
1,0.645132,0.638345,4.264571e-07,0.630673,0.592792,-0.019441,0.644290,0.541795,-0.028450,0.682910,...,0.736488,0.526884,-0.035484,0.723938,0.540022,-0.034202,0.710659,0.551803,-0.030152,Sissors
2,0.640712,0.644823,4.185136e-07,0.620354,0.601241,-0.016743,0.625203,0.549681,-0.025054,0.659432,...,0.719486,0.513861,-0.035997,0.707416,0.529387,-0.033411,0.695340,0.546181,-0.028114,Sissors
3,0.536404,0.619920,4.116136e-07,0.499182,0.625870,-0.025321,0.465530,0.598687,-0.037203,0.457701,...,0.473386,0.459782,-0.040711,0.481725,0.480981,-0.041110,0.490151,0.503639,-0.036479,Sissors
4,0.497161,0.580219,4.147568e-07,0.460030,0.586002,-0.020350,0.426831,0.560021,-0.028712,0.417785,...,0.437086,0.433737,-0.032320,0.443381,0.453562,-0.034293,0.450911,0.475329,-0.031802,Sissors

# 2. 데이터 분할하기

In [11]:
def encoding(label): 
    if label == "Sissors":
        return 0
    elif label == "Rock":
        return 1
    else:
        return 2
    
data["label_enc"] = data["label"].apply(lambda x: encoding(x))
data.head(2)

,x1,y1,z1,x2,y2,z2,x3,y3,z3,x4,...,y19,z19,x20,y20,z20,x21,y21,z21,label,label_enc
0,0.624676,0.634969,4.125314e-07,0.607056,0.590262,-0.019363,0.617399,0.537908,-0.028162,0.65457,...,0.514989,-0.034731,0.702284,0.528157,-0.034967,0.689110,0.540892,-0.032329,Sissors,0
1,0.645132,0.638345,4.264571e-07,0.630673,0.592792,-0.019441,0.644290,0.541795,-0.028450,0.68291,...,0.526884,-0.035484,0.723938,0.540022,-0.034202,0.710659,0.551803,-0.030152,Sissors,0

In [10]:
# X, y
X = data.iloc[:, :-2]
y = data["label_enc"]
print(X.shape, y.shape)

(118, 63) (118,)

In [13]:
# uv add scikit-learn
from sklearn.model_selection import train_test_split 

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42, shuffle=True)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(94, 63) (24, 63) (94,) (24,)

# 3. 모델 학습

In [14]:
# uv add xgboost
from xgboost import XGBClassifier
import numpy as np

model = XGBClassifier(n_estimators=10, random_state=42)
model.fit(np.array(X_train), np.array(y_train))

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=10,
              n_jobs=None, num_parallel_tree=None, ...)

# 4. 모델 성능 평가

In [15]:
from sklearn.metrics import classification_report 

y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.90      1.00      0.95         9
           1       1.00      1.00      1.00        10
           2       1.00      0.80      0.89         5

    accuracy                           0.96        24
   macro avg       0.97      0.93      0.95        24
weighted avg       0.96      0.96      0.96        24

# 5. 모델 내보내기

In [16]:
import joblib 

joblib.dump(model, "./scissors_rock_paper.pkl")

['./scissors_rock_paper.pkl']

In [18]:
# 모델 다시 불러올때에는?
import joblib 

model = joblib.load("./scissors_rock_paper.pkl")
model

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=None,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=10,
              n_jobs=None, num_parallel_tree=None, ...)